spring.application.name=apta-portal-backend

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/aptamp_db
spring.datasource.username=postgres
spring.datasource.password=Sruthi123@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true

# File upload limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# File storage directory
app.upload.dir=uploads
app.base-url=http://localhost:8082

# JWT config
app.jwt.secret=aptamp_super_secret_key_government_ap_2024_tennikoit_secure
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

spring.mvc.pathmatch.use-suffix-pattern=false